Add script
spine-generic/data-multi-subject pull request #112
Opened 2022-01-11 19:11 UTC by alexfoias

Add script to address https://github.com/spine-generic/data-multi-subject/issues/111

2022-01-11 20:37 UTC, jcohenadad requested changes
- pls add explicit title for the PR and in the body text of the PR
- pls add explanation of what the script does at the top of the python script

2022-01-19 16:46 UTC, alexfoias commented
This is the file used to push the info to the json files.[stats.csv](https://github.com/spine-generic/data-multi-subject/files/7898932/stats.csv)

2022-01-19 16:56 UTC, jcohenadad reviewed
You script `check_T2star_metadata.py` is very useful! 🏅

2022-01-19 16:58 UTC, jcohenadad approved these changes

2022-01-19 17:01 UTC, merged