Fix participants
spine-generic/data-multi-subject pull request #96
Opened 2021-09-27 20:26 UTC by alexfoias

Updated the information based on the information from our collaborators.

I tried to trace back when did the issue appear, but it was impossible due to the various changes in infrastructure.

2021-09-27 20:34 UTC, jcohenadad commented
> I tried to trace back when did the issue appear, but it was impossible due to the various changes in infrastructure.

you need to trace it back because we need to make sure:
- the participant IDs did not change (ie: the info given by Kouhei recently are valid for this BIDS dataset)
- this error did not happen for other datasets

so please, go back in time, look for emails, etc. document as much as possible. This is a very serious issue and we have a responsibility to not disseminate fake results.

2021-09-27 20:58 UTC, jcohenadad commented
> * this error did not happen for other datasets

e.g.: the tokyoIngenia values are also suspicious:

~~~
sub-tokyoIngenia01	M	25	-	-	2019-10-01	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
sub-tokyoIngenia02	F	32	-	-	2019-10-01	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
sub-tokyoIngenia03	M	36	-	-	2019-10-01	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
sub-tokyoIngenia04	F	29	-	-	2019-10-01	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
sub-tokyoIngenia05	F	28	-	-	2019-10-01	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
sub-tokyoIngenia06	M	24	-	-	2019-06-13	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
sub-tokyoIngenia07	M	35	-	-	2019-10-01	tokyo	Ingenia the University of Tokyo	Philips	Ingenia	-	5.3.1_5.3.1.1	"K. Kamiya, Y. Suzuki"
~~~

2021-09-29 18:49 UTC, alexfoias commented
I checked in all my emails. I could only find demographics for Juntendo. 

I think we received the data already converted to nifti.  In the email conversation with @jcohenadad with the subject `Re: Spinal cord generic protocol : consent from participants @ Tokyo Univ` sent on `Wed, Apr 3, 2019 at 1:40 PM`, I asked if we had the raw data, but I didn't get an answer. 

In the changes files, we don't have all the history of changes (the one from openeuro).

I don't know who added the data to the dataset.

2021-09-29 18:53 UTC, alexfoias commented
This error seemed to be in the initial commit on openneuro https://github.com/OpenNeuroDatasets/ds002902

2021-09-29 19:54 UTC, jcohenadad commented
> I checked in all my emails. I could only find demographics for Juntendo.
> 
> I think we received the data already converted to nifti. In the email conversation with @jcohenadad with the subject `Re: Spinal cord generic protocol : consent from participants @ Tokyo Univ` sent on `Wed, Apr 3, 2019 at 1:40 PM`, I asked if we had the raw data, but I didn't get an answer.

sorry for the oversight-- the answer is: no, we don't have the raw data

> In the changes files, we don't have all the history of changes (the one from openeuro).
> 
> I don't know who added the data to the dataset.

me neither

2021-09-29 19:57 UTC, jcohenadad commented
![image](https://user-images.githubusercontent.com/2482071/135339435-2a6c9eb9-5f66-4cad-ab60-882c416b42d2.png)

OK, we know these are the same subjects. So the last sanity check is to verify that the sub01 on tokyoIngenia corresponds to sub01 on tokyoSkyra, etc.  @alexfoias can you please do that (look at the T1w MRIs and you will easily find out if these are the same subjects)

2021-09-30 19:07 UTC, alexfoias commented
I did a visual checkout and the subjects seem to be correctly identified (similar anatomy for all 3 centers).

2021-11-10 22:16 UTC, jcohenadad approved these changes

2021-11-13 16:46 UTC, kousu requested changes
Because 

> we have a responsibility to not disseminate fake results.

this entire discussion needs to be summarized into the commit message before this is merged. Maybe even expanded, not summarized: include email addresses, institution names, URLs, dates, explanations, everything to explain where the error came from, how it was resolved.

That's the big benefit of using git diligently -- so that future us *can* trace back what happened to a dataset, and why.

2021-11-15 06:30 UTC, kousu commented
Hey, I fixed CI, so now we can actually talk about reviewing this properly.

2021-11-15 14:41 UTC, jcohenadad commented
> Should we delete https://openneuro.org/datasets/ds002902? Since it's wrong?

yes ( i thought we already did it @alexfoias ?)

> Should we rearrange the dataset to put all the data from the same physical people under the same

sorry i don't understand your suggestion-- what do you mean by "data from the same physical people"?

2021-11-15 16:03 UTC, alexfoias commented
I have removed all datasets from OpenNeuro. (This screenshot is take from the generic account used to create the datasets.)
![Screen Shot 2021-11-15 at 11 00 33 AM](https://user-images.githubusercontent.com/12564433/141814168-82266dd6-4fcb-4426-9ed8-dabfce080fbf.png)
.

2021-11-15 16:14 UTC, kousu commented
> I have removed all datasets from OpenNeuro.

:facepalm:  you're right. Okay, punting: https://github.com/OpenNeuroOrg/openneuro/issues/2484


> (This screenshot is take from the generic account used to create the datasets.)

By the way does anyone else have that credential? Does Julien? Should I? Better yet, can we make a Team on openneuro and all have our own credentials instead? Or are we giving up on OpenNeuro entirely?

2021-11-16 14:57 UTC, kousu commented
> > Should we delete https://openneuro.org/datasets/ds002902? Since it's wrong?
> 
> yes ( i thought we already did it @alexfoias ?)
> 

The older version is off OpenNeuro for good now: https://github.com/OpenNeuroOrg/openneuro/issues/2484


> > Should we rearrange the dataset to put all the data from the same physical people under the same
> 
> sorry i don't understand your suggestion-- what do you mean by "data from the same physical people"?

-> https://github.com/spine-generic/data-multi-subject/issues/102


Still **TODO**:

>     2. The `tokyoIngenia` values also need to be synchronized.

And `tokyo750w*` too!

>     1. What is "the information from our collaborators" that triggered this update? Who are they? Names and academic email addresses?
>     4. Let's make sure to write a relatively _detailed_ commit message justifying this change.

@alexfoias could we see the email that inspired this PR?

2021-11-16 15:31 UTC, kousu commented
New CI bug? https://github.com/spine-generic/data-multi-subject/runs/4226501836?check_suite_focus=true#step:11:2598

> ```
>  (recording state in git...)
> git-annex: get: 3 failed
> Error: Process completed with exit code 1.
> ```

Looks like maybe it's Amazon S3 having a minor outage?

https://github.com/spine-generic/data-multi-subject/runs/4226501836?check_suite_focus=true#step:11:620

```
get derivatives/labels/sub-stanford04/anat/sub-stanford04_acq-T1w_MTS_seg-manual.nii.gz (from amazon...) 
  download failed: Internal Server Error

  Unable to access these remotes: amazon

  Try making some of these repositories available:
  	5a5447a8-a9b8-49bc-8276-01a62632b502 -- [amazon]
   	5cdba4fc-8d50-4e89-bb0c-a3a4f9449666 -- julien@julien-macbook.local:~/code/spine-generic/data-multi-subject
   	9e4d13f3-30e1-4a29-8b86-670879928606 -- alex@NeuroPoly-MacBook-Pro.local:~/data/data-multi-subject

  (Note that these git remotes have annex-ignore set: origin)
failed
```

https://github.com/spine-generic/data-multi-subject/runs/4226501836?check_suite_focus=true#step:11:658

```
get derivatives/labels/sub-tehranS01/anat/sub-tehranS01_T1w_labels-disc-manual.nii.gz (from amazon...) 
  download failed: Internal Server Error

  Unable to access these remotes: amazon

  Try making some of these repositories available:
  	5a5447a8-a9b8-49bc-8276-01a62632b502 -- [amazon]
   	5cdba4fc-8d50-4e89-bb0c-a3a4f9449666 -- julien@julien-macbook.local:~/code/spine-generic/data-multi-subject
   	9e4d13f3-30e1-4a29-8b86-670879928606 -- alex@NeuroPoly-MacBook-Pro.local:~/data/data-multi-subject

  (Note that these git remotes have annex-ignore set: origin)
failed
```

https://github.com/spine-generic/data-multi-subject/runs/4226501836?check_suite_focus=true#step:11:711

```
get derivatives/labels/sub-tokyoSkyra03/anat/sub-tokyoSkyra03_T2star_rms_gmseg-manual.nii.gz (from amazon...) 
  download failed: Internal Server Error

  Unable to access these remotes: amazon

  Try making some of these repositories available:
  	5a5447a8-a9b8-49bc-8276-01a62632b502 -- [amazon]
   	5cdba4fc-8d50-4e89-bb0c-a3a4f9449666 -- julien@julien-macbook.local:~/code/spine-generic/data-multi-subject
   	9e4d13f3-30e1-4a29-8b86-670879928606 -- alex@NeuroPoly-MacBook-Pro.local:~/data/data-multi-subject

  (Note that these git remotes have annex-ignore set: origin)
failed
```

2021-11-17 21:11 UTC, alexfoias commented
@kousu Here is the info from the email:

Subject01 M 36 177cm 70kg
Subject02 M 36 168cm 80kg
Subject03 M 32 162cm 57kg
Subject04 F 34 161cm 65kg
Subject05 F 35 154cm 51kg
Subject06 F 30 160cm 48kg
Subject07 M 29 165cm 60kg

2022-01-19 16:51 UTC, jcohenadad commented
@alexfoias can you please update this PR after https://github.com/spine-generic/data-multi-subject/pull/112

2022-01-19 21:01 UTC, alexfoias reviewed
The values are the ones transferred by the collaborator.

2022-01-20 01:47 UTC, jcohenadad commented on participants.tsv
> +
```suggestion
```

2022-01-20 01:47 UTC, jcohenadad approved these changes

2022-01-20 01:47 UTC, merged